name: ShellCheck

on:
  pull_request:
    paths:
      - 'core/tabs/**/*.sh'
  workflow_dispatch:

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git fetch origin ${{ github.base_ref }}

      - name: Download and set up shellcheck
        run : |
          SC_URL="https://github.com/koalaman/shellcheck/releases/download/v0.10.0/shellcheck-v0.10.0.linux.x86_64.tar.xz"
          curl -fsSL "$SC_URL" | tar -Jx
          chmod +x "./shellcheck-v0.10.0/shellcheck"

      - name: Run shellcheck
        run: |
          error=0
          for file in $(git diff --name-only origin/${{ github.base_ref }} HEAD core/tabs); do
              if [[ "$file" == *.sh ]] && [[ -f "$file" ]]; then
                  sc_output=$(./shellcheck-v0.10.0/shellcheck -fgcc -Serror "$file")
                  parsed_errors=$(echo -e "$sc_output" | sed -n 's/\(.\+\)\:\([0-9]\+\)\:\([0-9]\+\)\: \(.*\)/::error file=\1,line=\2,col=\3::\4/p')
                  iter_safe_errors=$(echo "$parsed_errors" | sed 's/ /:space:/g')

                  for error in $iter_safe_errors; do
                      echo "$error" | sed 's/:space:/ /g'
                      error=1
                  done

                  tabs_detected=$(grep -nP '^\t+\w+' "$file")
                  parsed_tabs_detected=$(echo "$tabs_detected" | sed -n 's,\([0-9]\+\).*,::error file='"$file"'\,line=\1::Found tab indentations,p')
                  iter_safe_tabs_detected=$(echo "$parsed_tabs_detected" | sed 's/ /:space:/')

                  for error in $iter_safe_tabs_detected; do
                      echo "$error" | sed 's/:space:/ /g'
                      error=1
                  done
              fi
          done

          exit $error
