name: ShellCheck

on:
  pull_request:
    paths:
      - 'core/tabs/**/*.sh'
  workflow_dispatch:

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git fetch origin ${{ github.base_ref }}

      - name: Download and set up shellcheck
        run : |
          wget https://github.com/koalaman/shellcheck/releases/download/v0.10.0/shellcheck-v0.10.0.linux.x86_64.tar.xz
          tar -xf shellcheck-v0.10.0.linux.x86_64.tar.xz
          cd shellcheck-v0.10.0
          chmod +x shellcheck

      - name: Run shellcheck
        run: |
          error=0
          for file in $(git diff --name-only origin/${{ github.base_ref }} HEAD core/tabs); do
              if [[ "$file" == *.sh ]] && [[ -f "$file" ]]; then
                  errors="$(shellcheck -fgcc -Serror "$file" | sed -n 's/\(.\+\)\:\([0-9]\+\)\:\([0-9]\+\)\: \(.*\)/::error file=\1,line=\2,col=\3::\4/p' | sed 's/ /:space:/g')"
                          # ^--------- emit errors --------^   ^------------------ reformat info into gh action toolkit fn invocation ------------------^   ^ replace spaces  ^
                  for error in $errors; do
                      echo "$error" | sed 's/:space:/ /g'
                      error=1
                  done

                  errors="$(grep -nP '^\t+\w+' "$file" | sed -n 's,\([0-9]\+\).*,::error file='"$file"'\,line=\1::Found tab indentations,p' | sed 's/ /:space:/g')"
                  for error in $errors; do
                      echo "$error" | sed 's/:space:/ /g'
                      error=1
                  done
              fi
          done
          exit $error
